### PR TITLE
`RequireSameVersions` rule: consider entries in `<plugins>`  when analyzing build- and report-plugins

### LINKED ISSUE #372: RequireSameVersion: <plugins> not working
### Affected version

(at least) 3.3.0 onwards

### Bug description

The sample configuration of the `requireSameVersion` rule from the [documentation (`maven.apache.org`)](https://maven.apache.org/enforcer/enforcer-rules/requireSameVersions.html) does not work; this rule passes when it should fail:
```xml
<requireSameVersions>
    <plugins>
        <plugin>org.apache.maven.plugins:maven-surefire-plugin</plugin>
        <plugin>org.apache.maven.plugins:maven-failsafe-plugin</plugin>
        <plugin>org.apache.maven.plugins:maven-surefire-report-plugin</plugin>
    </plugins>
</requireSameVersions>
```

The rule works if we rewrite it as:
```xml
<requireSameVersions>
    <buildPlugins>
        <plugin>org.apache.maven.plugins:maven-surefire-plugin</plugin>
        <plugin>org.apache.maven.plugins:maven-failsafe-plugin</plugin>
    </buildPlugins>
    <reportPlugins>
        <plugin>org.apache.maven.plugins:maven-surefire-report-plugin</plugin>
    </reportPlugins>
</requireSameVersions>
```

### PR DESCRIPTION
**Pull request by turing85**
Resolves #372 

### `RequireSameVersion` rule
 if plugins are analyzed, entries under `<plugins>` must be considered f
Following this checklist to help us incorporate your
contribution quickly and easily:

- [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by turing85** [comment]
@slawekjaranowski I'd like to force-push one more time when the pipeline is green. I introduced the formatting error, and I would like to correct this properly.

File: enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireSameVersions.java [hunk 1]
```diff
@@ -69,10 +69,14 @@ public void execute() throws EnforcerRuleException {
         // consider including profile based artifacts
         Map<String, List<String>> versionMembers = new LinkedHashMap<>();
 
+        Set<String> allBuildPlugins = new HashSet<>(buildPlugins);
+        allBuildPlugins.addAll(plugins);
+        Set<String> allReportPlugins = new HashSet<>(reportPlugins);
+        allBuildPlugins.addAll(plugins);
```
Comment (slawekjaranowski) [inline enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireSameVersions.java:75]: `allBuildPlugins.addAll` -> `allReportPlugins.addAll`

unit test pass, looks like not covered something

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]

File: enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireSameVersions.java (hunk 1 above)
Comment (turing85) [reply enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireSameVersions.java]: Done.

**Comment by slawekjaranowski** [comment]
@turing85 thanks
